name: Weekly Twitter Sentiment Report

on:
  schedule:
    - cron: '30 8 * * MON'   # every Monday at 08:30 UTC
  workflow_dispatch:

jobs:
  build-report:
    runs-on: ubuntu-latest

    env:
      # Supabase
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      # Mailjet (unused unless SEND_EMAIL=true)
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}
      # Email toggle
      SEND_EMAIL:            "false"
      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      # 1) Checkout repo
      - uses: actions/checkout@v4

      # 2) System libraries (incl. GLPK + Chrome deps)
      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            ghostscript \
            libssl-dev libxml2-dev libcurl4-openssl-dev \
            libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev \
            libpng-dev libtiff5-dev libjpeg-dev libnss3 libxss1 \
            libglpk-dev

      # 3) Install pandoc (needed by rmarkdown)
      - uses: r-lib/actions/setup-pandoc@v2

      # 4) Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # 5) Headless Chrome for pagedown
      - name: Install headless Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      # 5b) Expose CHROME_BIN for R
      - name: Export CHROME_BIN
        run: echo "CHROME_BIN=${{ steps.chrome.outputs.chrome-path }}" >> "$GITHUB_ENV"

      # 6) Run the weekly pipeline
      - name: Run weekly sentiment script
        run: Rscript run_weekly_sentiment.R

      # 7) (Optional) archive the generated PDF + HTML
      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-sentiment-report
          path: |
            *.pdf
            *.html
          if-no-files-found: warn
